name: Axe accessibility testing

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Path to check (e.g. publications/)'
        required: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Get Chromium version
        run: echo "CHROMIUM_VERSION=$(wget -qO- https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE | cut -d. -f1)" >> $GITHUB_ENV
      - uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: ${{ env.CHROMIUM_VERSION }}
      - name: Run axe
        run: |
          npm install -g @axe-core/cli chromedriver@$CHROMIUM_VERSION
          npx astro preview --port 8080 &
          sleep 3
          axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver http://localhost:8080/${{ github.event.inputs.url }} --load-delay=1500 --exit
